skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
eumentus = "9x3boz9bPvwL1zfTMyDo3Qjv441TqCy7hQsjf2aWoW7x"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
